/**
 * @file AdminProductForm.jsx
 * @description Add/edit products with a Rich Text Editor for SOPs (Premium UI).
 */
"use client";
import React, { useState, useEffect } from "react";
import dynamic from "next/dynamic";
import { supabase } from "../utils/supabase";
import { UniversalInput } from "./ui/UniversalInput";
import { Button } from "./ui/BaseComponents";
import { t } from "../utils/dictionary";

// Dynamically import ReactQuill to prevent Next.js SSR (Server-Side Rendering) crash
const ReactQuill = dynamic(() => import("react-quill"), { ssr: false });
import "react-quill/dist/quill.snow.css";

export default function AdminProductForm() {
  const [name, setName] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [sortOrder, setSortOrder] = useState(0);
  const [isBase, setIsBase] = useState(false);
  const [baseProductId, setBaseProductId] = useState("");
  const [proofingTime, setProofingTime] = useState("");
  const [bakingTime, setBakingTime] = useState("");
  const [bakingTemp, setBakingTemp] = useState("");
  const [productionNotes, setProductionNotes] = useState("");
  const [recipe, setRecipe] = useState([{ ingredient_id: "", amount: "" }]);

  const [categories, setCategories] = useState([]);
  const [baseProducts, setBaseProducts] = useState([]);
  const [ingredientsList, setIngredientsList] = useState([]);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    async function fetchData() {
      const { data: cats } = await supabase
        .from("product_categories")
        .select("id, name")
        .order("sort_order");
      const { data: bases } = await supabase
        .from("products")
        .select("id, name")
        .eq("is_base", true)
        .order("name", { ascending: true });
      const { data: ings } = await supabase
        .from("ingredients")
        .select("id, name, unit")
        .order("name", { ascending: true });

      if (cats) setCategories(cats);
      if (bases) setBaseProducts(bases);
      if (ings)
        setIngredientsList(
          ings.map((i) => ({ id: i.id, name: `${i.name} (${i.unit})` })),
        );
    }
    fetchData();
  }, []);

  const handleRecipeChange = (index, field, value) => {
    const newRecipe = [...recipe];
    newRecipe[index][field] = value;
    setRecipe(newRecipe);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);

    const { data: newProduct, error: productError } = await supabase
      .from("products")
      .insert([
        {
          name,
          category_id: categoryId || null,
          sort_order: sortOrder,
          is_base: isBase,
          base_product_id: isBase ? null : baseProductId || null,
          proofing_time_mins: proofingTime || null,
          baking_time_mins: bakingTime || null,
          baking_temp_celsius: bakingTemp || null,
          production_notes: productionNotes || null, // Saves the HTML generated by Quill
        },
      ])
      .select()
      .single();

    if (productError) {
      alert(t("prod_alert_error") + productError.message);
      setIsLoading(false);
      return;
    }

    const validRecipes = recipe.filter((r) => r.ingredient_id && r.amount);
    if (validRecipes.length > 0) {
      const recipeInserts = validRecipes.map((r) => ({
        product_id: newProduct.id,
        ingredient_id: r.ingredient_id,
        amount_per_unit: r.amount,
      }));
      await supabase.from("gramasi_recipes").insert(recipeInserts);
    }

    alert(t("prod_alert_mapped"));
    setIsLoading(false);

    setName("");
    setCategoryId("");
    setSortOrder(0);
    setIsBase(false);
    setBaseProductId("");
    setProofingTime("");
    setBakingTime("");
    setBakingTemp("");
    setProductionNotes("");
    setRecipe([{ ingredient_id: "", amount: "" }]);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-8 max-w-4xl mx-auto pb-10">
      <div className="bg-white p-6 md:p-8 rounded-[2rem] shadow-sm border border-stone-200">
        <div className="mb-6 border-b border-stone-100 pb-4">
          <h2 className="text-2xl font-extrabold text-stone-800">
            {t("prod_form_title")}
          </h2>
          <p className="text-stone-500">{t("prod_form_sub")}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 mb-8">
          <div className="lg:col-span-2">
            <UniversalInput
              label={t("prod_name")}
              value={name}
              onChange={setName}
              required
              placeholder={t("prod_name_ph")}
            />
          </div>
          <div className="lg:col-span-2">
            <UniversalInput
              type="select"
              label={t("prod_cat")}
              value={categoryId}
              onChange={setCategoryId}
              options={categories}
              required
            />
          </div>
          <div className="lg:col-span-1">
            <UniversalInput
              type="number"
              label={t("prod_sort")}
              value={sortOrder}
              onChange={setSortOrder}
              required
            />
          </div>
        </div>

        {/* RICH TEXT EDITOR (QUILL) */}
        <div className="mb-8">
          <label className="text-xs font-bold text-stone-500 uppercase tracking-wide ml-1 mb-1.5 block">
            {t("prod_notes")} / SOP
          </label>
          <div className="bg-white rounded-xl border border-stone-200 overflow-hidden shadow-sm [&_.ql-toolbar]:bg-stone-50 [&_.ql-toolbar]:border-none [&_.ql-toolbar]:border-b [&_.ql-toolbar]:border-stone-200 [&_.ql-container]:border-none [&_.ql-editor]:min-h-[150px] [&_.ql-editor]:text-stone-700 [&_.ql-editor]:text-base">
            <ReactQuill
              theme="snow"
              value={productionNotes}
              onChange={setProductionNotes}
              placeholder={t("prod_notes_ph")}
            />
          </div>
        </div>

        <div className="p-5 bg-stone-50 rounded-2xl border border-stone-200 shadow-sm mb-8">
          <label className="flex items-center gap-3 cursor-pointer font-bold mb-4 text-stone-800 md:text-lg">
            <input
              type="checkbox"
              checked={isBase}
              onChange={(e) => {
                setIsBase(e.target.checked);
                setBaseProductId("");
              }}
              className="w-5 h-5 text-amber-600 rounded focus:ring-amber-500"
            />
            {t("prod_is_base_label")}
          </label>

          {!isBase && (
            <div className="md:w-1/2 mt-2">
              <UniversalInput
                type="select"
                label={t("prod_deducts_from")}
                value={baseProductId}
                onChange={setBaseProductId}
                options={baseProducts}
                placeholder={t("prod_deducts_ph")}
              />
            </div>
          )}
        </div>

        <div className="grid grid-cols-3 gap-4 mb-8">
          <UniversalInput
            type="number"
            label={t("prod_proof_min")}
            value={proofingTime}
            onChange={setProofingTime}
          />
          <UniversalInput
            type="number"
            label={t("prod_bake_min")}
            value={bakingTime}
            onChange={setBakingTime}
          />
          <UniversalInput
            type="number"
            label={t("prod_bake_temp")}
            value={bakingTemp}
            onChange={setBakingTemp}
          />
        </div>

        <div className="p-4 md:p-6 bg-stone-50 rounded-2xl border border-stone-200 shadow-inner">
          <div className="mb-5 border-b border-stone-200 pb-3 flex justify-between items-center">
            <div>
              <h3 className="font-extrabold text-stone-800 text-lg">
                {t("prod_recipe_title")}
              </h3>
              <p className="text-stone-500 text-sm hidden sm:block">
                {t("prod_recipe_sub")}
              </p>
            </div>
            <Button
              type="button"
              variant="secondary"
              onClick={() =>
                setRecipe([...recipe, { ingredient_id: "", amount: "" }])
              }
              className="text-sm px-4 py-2 h-auto bg-white shadow-sm"
            >
              + Bahan
            </Button>
          </div>

          <div className="space-y-4 mb-2">
            {recipe.map((row, index) => (
              <div
                key={index}
                className="relative p-4 md:p-5 bg-white rounded-xl border border-stone-200 shadow-sm"
              >
                <button
                  type="button"
                  onClick={() =>
                    setRecipe(recipe.filter((_, i) => i !== index))
                  }
                  className="absolute top-2 right-2 p-2 text-stone-300 hover:text-red-500 transition-colors"
                  title="Hapus"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fillRule="evenodd"
                      d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                      clipRule="evenodd"
                    />
                  </svg>
                </button>

                <div className="flex flex-col md:flex-row gap-4 mt-2 pr-6">
                  <div className="flex-1">
                    <UniversalInput
                      type="select"
                      label={t("prod_ing_label")}
                      value={row.ingredient_id}
                      onChange={(val) =>
                        handleRecipeChange(index, "ingredient_id", val)
                      }
                      options={ingredientsList}
                    />
                  </div>
                  <div className="w-full md:w-32">
                    <UniversalInput
                      type="number"
                      label={t("prod_amount_label")}
                      value={row.amount}
                      onChange={(val) =>
                        handleRecipeChange(index, "amount", val)
                      }
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <Button
        type="submit"
        variant="primary"
        isLoading={isLoading}
        className="w-full py-4 text-lg font-bold shadow-lg hover:scale-[1.01] transition-transform"
      >
        {t("prod_btn_save")}
      </Button>
    </form>
  );
}
